# window size
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# room size
GENERATE_RANDOM_ROOM = True
ROOM_WIDTH = 800
ROOM_HEIGHT = 600
ROOM_SQUARE = ROOM_WIDTH * ROOM_HEIGHT
ROOM_DEPTH = 270
WALLS_WIDTH = 10
SCALE = 1

# How many times generate room with furniture objects
MAIN_ITERATIONS = 5

# COLLISION_PENALTY
COLLISION_PENALTY = 100_000_000

# controls
X_OFFSET = (SCREEN_WIDTH - ROOM_WIDTH) // 2
Y_OFFSET = (SCREEN_HEIGHT - ROOM_HEIGHT) // 2
DEBUG = False
S_DEBUG = False
START_GA = True
DEBUG_EVERY_N = True
FPS_IN_EVERY_N = 18
STOP_WHEN_REACHED = 1.1

# for pygame draw
FONT, CLOCK, SCREEN = None, None, None
ALL_OBJECTS, FURNITURE_OBJECTS, SPRITE_ORDER = list(), list(), list()
CURRENT_GA_SPRITE = None

# For GA
MAX_NUM_ITERATION = 600
POPULATION_SIZE = 100
MAX_ITERATION_WITHOUT_IMPROV = 200
MUTATION_PROBABILITY = 0.50     # default 0.1 = 10%
PARENTS_PORTION = 0.05          # default 0.30 = 30%
ELIT_RATIO = PARENTS_PORTION    # default 0.01 = 1%
